### ISSUE TITLE
Automated front end testing

### ISSUE THREAD

**Issue by iewil** [opendocsg/opendoc-theme#23]
- [x] Travis setup for Desktop screenshotting
- [ ] Currently failing due to max number of parallel automated tests (1), may need to move to pure automation to run multiple scripts together and take screenshots

**Comment by pregnantboy** [comment]
1. [Percy.io](https://percy.io)
2. [SauceLabs](https://saucelabs.com/products/web-testing/cross-browser-testing)
3. [CrossBrowserTesting](https://crossbrowsertesting.com/selenium-testing)
4. [BrowserStack](https://www.browserstack.com/)
5. [LambdaTest](https://www.lambdatest.com/)

**Comment by pregnantboy** [comment]
On hold for now
