### ISSUE TITLE
when a user presses the "enter" key in the search bar, there should be some feedback to let the user know that the search is taking place

### ISSUE THREAD

**Issue by iewil** [opendocsg/opendoc-theme#51]

**Comment by pregnantboy** [comment]
Enter doesnt do anything. it's search-as-you-type

**Comment by iewil** [comment]
yes, but that's not obvious to the user. he tried pressing enter multiple times after he completed typing even though the search results were already displayed. The feedback from the enter button won't do anything, but it will help to assure the user that the search is working. not a road blocker, but more of a user experience tweak
